<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $codigoPostal = [
            ['name'=>'Álvaro Obregón','cost'=>'100.00','department_id'=>1],
            ['name'=>'Azcapotzalco','cost'=>'100.00','department_id'=>1],
            ['name'=>'Benito Juárez','cost'=>'100.00','department_id'=>1],
            ['name'=>'Coyoacán','cost'=>'100.00','department_id'=>1],
            ['name'=>'Cuajimalpa de Morelos','cost'=>'100.00','department_id'=>1],
            ['name'=>'Cuauhtémoc','cost'=>'100.00','department_id'=>1],
            ['name'=>'Gustavo A. Madero','cost'=>'100.00','department_id'=>1],
            ['name'=>'Iztacalco','cost'=>'100.00','department_id'=>1],
            ['name'=>'Iztapalapa','cost'=>'100.00','department_id'=>1],
            ['name'=>'La Magdalena Contreras','cost'=>'100.00','department_id'=>1],
            ['name'=>'Miguel Hidalgo','cost'=>'100.00','department_id'=>1],
            ['name'=>'Milpa Alta','cost'=>'100.00','department_id'=>1],
            ['name'=>'Tláhuac','cost'=>'100.00','department_id'=>1],
            ['name'=>'Tlalpan','cost'=>'100.00','department_id'=>1],
            ['name'=>'Venustiano Carranza','cost'=>'100.00','department_id'=>1],
            ['name'=>'Xochimilco','cost'=>'100.00','department_id'=>1],
            ['name'=>'Toluca','cost'=>'100.00','department_id'=>2],
            ['name'=>'Acambay de Ruíz Castañeda','cost'=>'100.00','department_id'=>2],
            ['name'=>'Aculco','cost'=>'100.00','department_id'=>2],
            ['name'=>'Temascalcingo','cost'=>'100.00','department_id'=>2],
            ['name'=>'Atlacomulco','cost'=>'100.00','department_id'=>2],
            ['name'=>'Timilpan','cost'=>'100.00','department_id'=>2],
            ['name'=>'Morelos','cost'=>'100.00','department_id'=>2],
            ['name'=>'El Oro','cost'=>'100.00','department_id'=>2],
            ['name'=>'San Felipe del Progreso','cost'=>'100.00','department_id'=>2],
            ['name'=>'San José del Rincón','cost'=>'100.00','department_id'=>2],
            ['name'=>'Jocotitlán','cost'=>'100.00','department_id'=>2],
            ['name'=>'Ixtlahuaca','cost'=>'100.00','department_id'=>2],
            ['name'=>'Jiquipilco','cost'=>'100.00','department_id'=>2],
            ['name'=>'Temoaya','cost'=>'100.00','department_id'=>2],
            ['name'=>'Almoloya de Juárez','cost'=>'100.00','department_id'=>2],
            ['name'=>'Villa Victoria','cost'=>'100.00','department_id'=>2],
            ['name'=>'Villa de Allende','cost'=>'100.00','department_id'=>2],
            ['name'=>'Donato Guerra','cost'=>'100.00','department_id'=>2],
            ['name'=>'Ixtapan del Oro','cost'=>'100.00','department_id'=>2],
            ['name'=>'Santo Tomás','cost'=>'100.00','department_id'=>2],
            ['name'=>'Otzoloapan','cost'=>'100.00','department_id'=>2],
            ['name'=>'Zacazonapan','cost'=>'100.00','department_id'=>2],
            ['name'=>'Valle de Bravo','cost'=>'100.00','department_id'=>2],
            ['name'=>'Amanalco','cost'=>'100.00','department_id'=>2],
            ['name'=>'Temascaltepec','cost'=>'100.00','department_id'=>2],
            ['name'=>'Zinacantepec','cost'=>'100.00','department_id'=>2],
            ['name'=>'Tejupilco','cost'=>'100.00','department_id'=>2],
            ['name'=>'Luvianos','cost'=>'100.00','department_id'=>2],
            ['name'=>'San Simón de Guerrero','cost'=>'100.00','department_id'=>2],
            ['name'=>'Amatepec','cost'=>'100.00','department_id'=>2],
            ['name'=>'Tlatlaya','cost'=>'100.00','department_id'=>2],
            ['name'=>'Sultepec','cost'=>'100.00','department_id'=>2],
            ['name'=>'Texcaltitlán','cost'=>'100.00','department_id'=>2],
            ['name'=>'Coatepec Harinas','cost'=>'100.00','department_id'=>2],
            ['name'=>'Villa Guerrero','cost'=>'100.00','department_id'=>2],
            ['name'=>'Zacualpan','cost'=>'100.00','department_id'=>2],
            ['name'=>'Almoloya de Alquisiras','cost'=>'100.00','department_id'=>2],
            ['name'=>'Ixtapan de la Sal','cost'=>'100.00','department_id'=>2],
            ['name'=>'Tonatico','cost'=>'100.00','department_id'=>2],
            ['name'=>'Zumpahuacán','cost'=>'100.00','department_id'=>2],
            ['name'=>'Lerma','cost'=>'100.00','department_id'=>2],
            ['name'=>'Xonacatlán','cost'=>'100.00','department_id'=>2],
            ['name'=>'Otzolotepec','cost'=>'100.00','department_id'=>2],
            ['name'=>'San Mateo Atenco','cost'=>'100.00','department_id'=>2],
            ['name'=>'Metepec','cost'=>'100.00','department_id'=>2],
            ['name'=>'Mexicaltzingo','cost'=>'100.00','department_id'=>2],
            ['name'=>'Calimaya','cost'=>'100.00','department_id'=>2],
            ['name'=>'Chapultepec','cost'=>'100.00','department_id'=>2],
            ['name'=>'San Antonio la Isla','cost'=>'100.00','department_id'=>2],
            ['name'=>'Tenango del Valle','cost'=>'100.00','department_id'=>2],
            ['name'=>'Rayón','cost'=>'100.00','department_id'=>2],
            ['name'=>'Joquicingo','cost'=>'100.00','department_id'=>2],
            ['name'=>'Tenancingo','cost'=>'100.00','department_id'=>2],
            ['name'=>'Malinalco','cost'=>'100.00','department_id'=>2],
            ['name'=>'Ocuilan','cost'=>'100.00','department_id'=>2],
            ['name'=>'Atizapán','cost'=>'100.00','department_id'=>2],
            ['name'=>'Almoloya del Río','cost'=>'100.00','department_id'=>2],
            ['name'=>'Texcalyacac','cost'=>'100.00','department_id'=>2],
            ['name'=>'Tianguistenco','cost'=>'100.00','department_id'=>2],
            ['name'=>'Xalatlaco','cost'=>'100.00','department_id'=>2],
            ['name'=>'Capulhuac','cost'=>'100.00','department_id'=>2],
            ['name'=>'Ocoyoacac','cost'=>'100.00','department_id'=>2],
            ['name'=>'Huixquilucan','cost'=>'100.00','department_id'=>2],
            ['name'=>'Atizapán de Zaragoza','cost'=>'100.00','department_id'=>2],
            ['name'=>'Naucalpan de Juárez','cost'=>'100.00','department_id'=>2],
            ['name'=>'Tlalnepantla de Baz','cost'=>'100.00','department_id'=>2],
            ['name'=>'Polotitlán','cost'=>'100.00','department_id'=>2],
            ['name'=>'Jilotepec','cost'=>'100.00','department_id'=>2],
            ['name'=>'Soyaniquilpan de Juárez','cost'=>'100.00','department_id'=>2],
            ['name'=>'Villa del Carbón','cost'=>'100.00','department_id'=>2],
            ['name'=>'Chapa de Mota','cost'=>'100.00','department_id'=>2],
            ['name'=>'Nicolás Romero','cost'=>'100.00','department_id'=>2],
            ['name'=>'Isidro Fabela','cost'=>'100.00','department_id'=>2],
            ['name'=>'Jilotzingo','cost'=>'100.00','department_id'=>2],
            ['name'=>'Tepotzotlán','cost'=>'100.00','department_id'=>2],
            ['name'=>'Coyotepec','cost'=>'100.00','department_id'=>2],
            ['name'=>'Huehuetoca','cost'=>'100.00','department_id'=>2],
            ['name'=>'Cuautitlán Izcalli','cost'=>'100.00','department_id'=>2],
            ['name'=>'Teoloyucan','cost'=>'100.00','department_id'=>2],
            ['name'=>'Cuautitlán','cost'=>'100.00','department_id'=>2],
            ['name'=>'Melchor Ocampo','cost'=>'100.00','department_id'=>2],
            ['name'=>'Tultitlán','cost'=>'100.00','department_id'=>2],
            ['name'=>'Tultepec','cost'=>'100.00','department_id'=>2],
            ['name'=>'Ecatepec de Morelos','cost'=>'100.00','department_id'=>2],
            ['name'=>'Zumpango','cost'=>'100.00','department_id'=>2],
            ['name'=>'Tequixquiac','cost'=>'100.00','department_id'=>2],
            ['name'=>'Apaxco','cost'=>'100.00','department_id'=>2],
            ['name'=>'Hueypoxtla','cost'=>'100.00','department_id'=>2],
            ['name'=>'Coacalco de Berriozábal','cost'=>'100.00','department_id'=>2],
            ['name'=>'Tecámac','cost'=>'100.00','department_id'=>2],
            ['name'=>'Jaltenco','cost'=>'100.00','department_id'=>2],
            ['name'=>'Tonanitla','cost'=>'100.00','department_id'=>2],
            ['name'=>'Nextlalpan','cost'=>'100.00','department_id'=>2],
            ['name'=>'Teotihuacán','cost'=>'100.00','department_id'=>2],
            ['name'=>'San Martín de las Pirámides','cost'=>'100.00','department_id'=>2],
            ['name'=>'Acolman','cost'=>'100.00','department_id'=>2],
            ['name'=>'Otumba','cost'=>'100.00','department_id'=>2],
            ['name'=>'Axapusco','cost'=>'100.00','department_id'=>2],
            ['name'=>'Nopaltepec','cost'=>'100.00','department_id'=>2],
            ['name'=>'Temascalapa','cost'=>'100.00','department_id'=>2],
            ['name'=>'Tezoyuca','cost'=>'100.00','department_id'=>2],
            ['name'=>'Chiautla','cost'=>'100.00','department_id'=>2],
            ['name'=>'Papalotla','cost'=>'100.00','department_id'=>2],
            ['name'=>'Tepetlaoxtoc','cost'=>'100.00','department_id'=>2],
            ['name'=>'Texcoco','cost'=>'100.00','department_id'=>2],
            ['name'=>'Chiconcuac','cost'=>'100.00','department_id'=>2],
            ['name'=>'Atenco','cost'=>'100.00','department_id'=>2],
            ['name'=>'Chimalhuacán','cost'=>'100.00','department_id'=>2],
            ['name'=>'Chicoloapan','cost'=>'100.00','department_id'=>2],
            ['name'=>'La Paz','cost'=>'100.00','department_id'=>2],
            ['name'=>'Ixtapaluca','cost'=>'100.00','department_id'=>2],
            ['name'=>'Chalco','cost'=>'100.00','department_id'=>2],
            ['name'=>'Valle de Chalco Solidaridad','cost'=>'100.00','department_id'=>2],
            ['name'=>'Temamatla','cost'=>'100.00','department_id'=>2],
            ['name'=>'Cocotitlán','cost'=>'100.00','department_id'=>2],
            ['name'=>'Tlalmanalco','cost'=>'100.00','department_id'=>2],
            ['name'=>'Ayapango','cost'=>'100.00','department_id'=>2],
            ['name'=>'Tenango del Aire','cost'=>'100.00','department_id'=>2],
            ['name'=>'Ozumba','cost'=>'100.00','department_id'=>2],
            ['name'=>'Juchitepec','cost'=>'100.00','department_id'=>2],
            ['name'=>'Tepetlixpa','cost'=>'100.00','department_id'=>2],
            ['name'=>'Amecameca','cost'=>'100.00','department_id'=>2],
            ['name'=>'Atlautla','cost'=>'100.00','department_id'=>2],
            ['name'=>'Ecatzingo','cost'=>'100.00','department_id'=>2],
            ['name'=>'Nezahualcóyotl','cost'=>'100.00','department_id'=>2],

        ];

        foreach ($codigoPostal as $codigop) {
         City::create($codigop); 
        }
    }
}
